name: Bug Report
description: Submit a bug
title: "Bug: <Title>"
labels: ["Type: Bug"]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear description of what the bug is. Please add pictures or videos! Also if this a performance-related bug report, please state your CPU, GPU and the amount + speed of your RAM.
    placeholder: |
      When I do X then Y happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue Map
    description: A map that the issue occurs on. 
    placeholder: |
      Please explicitly state what map the issue occurs on. If it's a generic issue, then state a map which can easily reproduce the bug.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Open map ...
      2. Do ...
      3. See error
  validations:
    required: true
